image: gradle:8.5.0-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - test
  - build
  - deploy


build:
  stage: build
  tags:
    - docker
  script:
    - gradle assemble


test:
  stage: test
  tags:
    - docker
  script:
    - gradle test

deploy:
  stage: deploy
  image: docker:latest
  tags:
    - docker
  script:
    - export DOCKER_HOST=tcp://$DOCKER_DEAMON_IP:2375
    - docker build -t $DOCKER_USER_NAME/$DOCKER_IMAGE_NAME .