variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


stages:
  - test
  - build

build:
  stage: build
  script:
    - ./gradlew assemble
test:
  stage: test
  script:
    - ./gradlew test