image: gradle:8.5.0-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

before_script:
  - chmod +x ./gradlew

stages:
  - test
  - build

cache:
  paths:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/


build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assemble
test:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew test